"""initial

Revision ID: caee1ee16f94
Revises: 
Create Date: 2026-02-17 20:14:54.645637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee1ee16f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('specialite', sa.Enum('Médecine Générale', 'Cardiologie', 'Pneumologie', 'Neurologie', 'Gynécologie', 'Pédiatrie', 'Dermatologie', 'Ophtalmologie', 'ORL', 'Traumatologie', 'Endocrinologie', 'Hépato-Gastroentérologie', name='specialite_enum'), nullable=False),
    sa.Column('matricule', sa.String(length=40), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.Enum('Masculin', 'Féminin', name='sexe_enum'), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('groupe_sanguin', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='groupe_sanguin_enum'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('antecedents', sa.Text(), nullable=True),
    sa.Column('medecin_ref_id', sa.Integer(), nullable=True),
    sa.Column('assurance', sa.String(length=80), nullable=True),
    sa.Column('num_assurance', sa.String(length=60), nullable=True),
    sa.Column('photo_color', sa.String(length=10), nullable=False, comment="Code couleur hexadécimal affiché dans l'avatar frontend"),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_ref_id'], ['medecins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patient_nom_prenom', ['nom', 'prenom'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_medecin_ref_id'), ['medecin_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_prenom'), ['prenom'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'medecin', 'secretaire', 'infirmier', name='user_role_enum'), nullable=False),
    sa.Column('role_label', sa.String(length=120), nullable=True),
    sa.Column('photo_color', sa.String(length=10), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_medecin_id'), ['medecin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure', sa.Time(), nullable=True),
    sa.Column('type_consult', sa.Enum('Consultation initiale', 'Consultation de suivi', 'Urgence', 'Téléconsultation', 'Bilan', 'Consultation pré-opératoire', name='type_consult_enum'), nullable=False, comment="maps to 'type' in frontend (type est réservé en Python/SQL)"),
    sa.Column('specialite', sa.Enum('Médecine Générale', 'Cardiologie', 'Pneumologie', 'Neurologie', 'Gynécologie', 'Pédiatrie', 'Dermatologie', 'Ophtalmologie', 'ORL', 'Traumatologie', 'Endocrinologie', 'Hépato-Gastroentérologie', name='specialite_enum'), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('Planifiée', 'En cours', 'Terminée', 'Annulée', name='statut_consult_enum'), nullable=False),
    sa.Column('poids', sa.Numeric(precision=5, scale=2), nullable=True, comment='kg'),
    sa.Column('taille', sa.Numeric(precision=5, scale=1), nullable=True, comment='cm'),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True, comment='°C'),
    sa.Column('pouls', sa.SmallInteger(), nullable=True, comment='bpm'),
    sa.Column('saturation', sa.Numeric(precision=4, scale=1), nullable=True, comment='% SpO₂'),
    sa.Column('tension', sa.String(length=20), nullable=True, comment='ex. 130/80 mmHg'),
    sa.Column('notes_cliniques', sa.Text(), nullable=True, comment="maps to 'notes' in frontend"),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('ordonnance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index('ix_consult_date_statut', ['date', 'statut'], unique=False)
        batch_op.create_index('ix_consult_patient_date', ['patient_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_medecin_id'), ['medecin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_statut'), ['statut'], unique=False)

    op.create_table('examens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type_examen', sa.Enum('Biologie', 'Imagerie', 'Cardiologie', 'Neurologie', 'Ophtalmologie', 'Microbiologie', 'Anatomo-pathologie', 'Autre', name='type_examen_enum'), nullable=False, comment="maps to 'type' in frontend"),
    sa.Column('nom', sa.String(length=200), nullable=False, comment="Nom de l'examen, ex. 'NFS', 'Radiographie thoracique F+P'"),
    sa.Column('statut', sa.Enum('En attente', "En cours d'analyse", 'Résultat disponible', name='statut_examen_enum'), nullable=False),
    sa.Column('resultat', sa.Text(), nullable=True, comment="Résultats textuels de l'examen"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.create_index('ix_examen_patient_date', ['patient_id', 'date'], unique=False)
        batch_op.create_index('ix_examen_statut', ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_medecin_id'), ['medecin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_statut'), ['statut'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examens_statut'))
        batch_op.drop_index(batch_op.f('ix_examens_patient_id'))
        batch_op.drop_index(batch_op.f('ix_examens_medecin_id'))
        batch_op.drop_index(batch_op.f('ix_examens_date'))
        batch_op.drop_index(batch_op.f('ix_examens_consultation_id'))
        batch_op.drop_index('ix_examen_statut')
        batch_op.drop_index('ix_examen_patient_date')

    op.drop_table('examens')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_statut'))
        batch_op.drop_index(batch_op.f('ix_consultations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_medecin_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_date'))
        batch_op.drop_index('ix_consult_patient_date')
        batch_op.drop_index('ix_consult_date_statut')

    op.drop_table('consultations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_medecin_id'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_prenom'))
        batch_op.drop_index(batch_op.f('ix_patients_nom'))
        batch_op.drop_index(batch_op.f('ix_patients_medecin_ref_id'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index('ix_patient_nom_prenom')

    op.drop_table('patients')
    op.drop_table('medecins')
    # ### end Alembic commands ###
